// Copyright (c) 2020 Proton Technologies AG
//
// This file is part of ProtonMail Bridge.
//
// ProtonMail Bridge is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// ProtonMail Bridge is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with ProtonMail Bridge.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by ./release-notes.sh at 'Thu Oct 29 12:57:32 PM CET 2020'. DO NOT EDIT.

package importexport

const ReleaseNotes = `• Improvements to the import from large mbox files with multiple labels
• Not allow to run multiple instances of the app or transfers at the same time
• Various enhancements of the import process related to parsing
• Cosmetic GUI changes
• Better error handling
`

const ReleaseFixedBugs = `• Linux font issues - Fedora specific
• App response to the user pausing and canceling import or export
• Handling errors during update
`
