// Copyright (c) 2020 Proton Technologies AG
//
// This file is part of ProtonMail Bridge.
//
// ProtonMail Bridge is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// ProtonMail Bridge is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with ProtonMail Bridge.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by ./release-notes.sh at 'Fri Sep 11 09:30:51 AM CEST 2020'. DO NOT EDIT.

package importexport

const ReleaseNotes = `***Note: If you were using the Import-Export app before, you need to uninstall the older version and log in again to the new version***

• Complete code refactor in preparation of stable and open source release of the Import-Export app
• Increased number of supported mail providers by changing the way the folder structures are handled (NIL hierarchy delimiter)
• Improved handling for unstable internet and pause and resume behavior
`

const ReleaseFixedBugs = `• Fixed rare cases where the application freezes when starting/stopping imports
• Allowed current date to be included in the selected date range for both import and export
• Improved manual update process
• Limit space usage by on device application logs
`
